language: python
python:
  - "3.4"
  - "2.7"
install:
  - python setup.py install && python setup.py develop easy_install gitchangelog[test]
  - pip install coverage coveralls
script:
  - git fetch --unshallow && pip install git+file://$PWD
  - git reset --hard HEAD ; git clean -d -f ; python setup.py sdist --formats=gztar && pip install dist/gitchangelog-$(./autogen.sh --get-version | tr "_" "-").tar.gz --upgrade
  - pip uninstall -y "$(./autogen.sh --get-name)"
  - nosetests .
after_success:
  - coveralls
